openapi: 3.0.3
info:
  title: GitHub Actions – Artifacts (Minimal)
  version: 1.0.0
  description: |
    Minimal endpoints to fetch the latest workflow run and its artifacts for a branch.
    Auth: Personal Access Token (classic or fine-grained) with repo read: `Authorization: Bearer <token>`
servers:
  - url: https://api.github.com
paths:
  /repos/{owner}/{repo}/actions/runs:
    get:
      operationId: listWorkflowRuns
      summary: List workflow runs (optionally filter by branch and status)
      parameters:
        - in: path
          name: owner
          required: true
          schema: { type: string }
        - in: path
          name: repo
          required: true
          schema: { type: string }
        - in: query
          name: branch
          required: false
          schema: { type: string }
        - in: query
          name: status
          required: false
          schema:
            type: string
            enum: [queued, in_progress, completed]
        - in: query
          name: per_page
          required: false
          schema: { type: integer, default: 10 }
      responses:
        '200':
          description: OK
  /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts:
    get:
      operationId: listArtifactsForRun
      summary: List artifacts generated by a workflow run
      parameters:
        - in: path
          name: owner
          required: true
          schema: { type: string }
        - in: path
          name: repo
          required: true
          schema: { type: string }
        - in: path
          name: run_id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
  /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}:
    get:
      operationId: downloadArtifact
      summary: Get a short-lived redirect URL to download an artifact archive
      parameters:
        - in: path
          name: owner
          required: true
          schema: { type: string }
        - in: path
          name: repo
          required: true
          schema: { type: string }
        - in: path
          name: artifact_id
          required: true
          schema: { type: integer }
        - in: path
          name: archive_format
          required: true
          schema:
            type: string
            enum: [zip]
      responses:
        '302':
          description: Redirect to time-limited artifact URL
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
