openapi: 3.1.0
info:
  title: GitHub Minimal
  version: 1.0.0
paths:
  /repos/{owner}/{repo}/pulls:
    post:
      operationId: github.pr_create
      summary: Create pull request (draft by default)
      parameters:
        - in: path
          name: owner
          required: true
          schema: { type: string }
        - in: path
          name: repo
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, head, base]
              properties:
                title: { type: string }
                head: { type: string }   # branch
                base: { type: string }   # default branch
                body: { type: string }
                draft: { type: boolean, default: true }
      responses:
        "201":
          description: Created
  /repos/{owner}/{repo}/issues/{number}/comments:
    post:
      operationId: github.comment_create
      summary: Add PR/issue comment
      parameters:
        - in: path
          name: owner
          required: true
          schema: { type: string }
        - in: path
          name: repo
          required: true
          schema: { type: string }
        - in: path
          name: number
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [body]
              properties:
                body: { type: string }
      responses:
        "201":
          description: Created
