openapi: 3.1.0
info:
  title: Test Runner
  version: 1.0.0
paths:
  /test/run:
    post:
      operationId: test.run
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  description: Default: npm test -- --reporters=jest-junit
      responses:
        "200":
          description: "OK; artifacts produced: junit.xml, coverage/*"
