name: agent-checks
on:
  pull_request:
    branches: [ main ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
        working-directory: sample-app
      - name: Unit tests (junit + coverage)
        run: npm test -- --coverage --reporters=default --reporters=jest-junit
        working-directory: sample-app
        env:
          JEST_JUNIT_OUTPUT: junit.xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: sample-app/coverage
      - name: Semantic Eval
        run: node ../scripts/semantic-eval.mjs
        working-directory: sample-app
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
